POST http://localhost:3000/todo/me
content-type: application/json

{
    "name": "Akash",
    "email": "akashlinux2003@gmail.com",
    "password": "akash"
}

"routes": [
    {
      "src": "/(.*)",
      "dest": "src/main.ts",
      "methods": ["GET", "POST", "PUT", "DELETE", "PATCH"],
      "headers": {
        "Access-Control-Allow-Origin": "*"
      },
      "continue": true
    },
    {
      "src": "/auth",
      "methods": ["POST"],
      "dest": "src/main.ts",
      "headers": {
        "Access-Control-Allow-Origin": "*"
      }
    }
  ]